{{ if eq .Values.env "prod" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-site-apex-proxy
  labels:
    app: site
    component: apex-proxy
    env: {{ .Values.env }}
spec:
  selector:
    app: site
    component: apex-proxy
    env: {{ .Values.env }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
{{ end }}
